---
- name: Install and configure OpenJDK, Docker, and AWS CLI on Ubuntu
  hosts: ubuntu_servers
  become: yes
  gather_facts: yes

  tasks:
    # Docker installation tasks
    - name: Install required system packages for Docker
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present
        update_cache: yes

    - name: Install Docker packages
      ansible.builtin.apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: present

    - name: Add current user to docker group
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    - name: Start and enable Docker service
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    # AWS CLI installation tasks
    - name: Install AWS CLI dependencies
      ansible.builtin.apt:
        name:
          - unzip
          - python3-pip
        state: present

    - name: Download AWS CLI v2
      ansible.builtin.get_url:
        url: https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip
        dest: /tmp/awscliv2.zip
        mode: '0755'

    - name: Unzip AWS CLI
      ansible.builtin.unarchive:
        src: /tmp/awscliv2.zip
        dest: /tmp
        remote_src: yes

    - name: Install AWS CLI
      ansible.builtin.command: /tmp/aws/install
      args:
        creates: /usr/local/bin/aws

    - name: Clean up AWS CLI installation files
      ansible.builtin.file:
        path: /tmp/awscliv2.zip
        state: absent
      ignore_errors: yes

    - name: Clean up extracted AWS CLI files
      ansible.builtin.file:
        path: /tmp/aws
        state: absent
      ignore_errors: yes

  